(define sum (lambda (x y z) (+ x y z)))
(define identity (lambda (x) x))
(define true (lambda (x y) x))
(define false (lambda (x y) y))
(define twice (lambda (x) (* 2 x)))
(define repeat (lambda (f) (lambda (y) (f (f y)))))
(define verbose (lambda (f) (lambda (y) (f y))))
(define hold (lambda (y) (lambda (f) (f y))))

;; Lambda Tests
;; (sum 10 20 30)
;; (sum 10 (* 2 10) 30)
;; (sum (* 2 5) (* 2 10) 30)
;; (identity 5)
;; (identity (identity 5))
;; ((verbose identity) 5)
;; ((verbose (verbose identity)) 5)
;; ((identity identity) 5)
;; (twice (identity 5))
;; (twice ((verbose identity) 5))
;; ((repeat identity) 5)
;; ((repeat twice) 5)
;; ((repeat (repeat twice)) 5)
;; (((repeat repeat) twice) 5)
;; ((repeat twice) ((repeat identity) 5))
;; ((hold 5) identity)

;; ;; Conditional Tests
;; (if #t 5 0)
;; (if #f 5 0)
;; (if #t 5)
;; (if #f 5)
;; (if #t (+ 2 2))
;; (if (eq 5 5) 5)
;; (identity (if #t 5))
;; (identity (twice (if #t 5)))
;; ((if #t identity) 5)
((if #t (verbose identity)) 5)
;; ((verbose (verbose (if #t identity))) 5)
